### PR TITLE
Update versions

### PR DESCRIPTION
**Pull request by puneet-pdx**
- Update versions - 
   Android Gradle Plugin Version - 4.1.2
   Gradle version - 6.5
   ArcGIS runtime version - 100.10.0
   test runner version
   materialLibraryVersion
   appcompatLibraryVersion
   constraintLayout version

### CODE REVIEW

**Review by sorenoid — APPROVED** [review]
👍

**Review by esreli — CHANGES_REQUESTED** [review]
It looks like the project has been updated appropriately. Thanks for checking that the app still works as expected after updating Runtime and dependencies.

### README

- [Solo.takeScreenshot()](https://github.com/Esri/mapbook-android/tree/puneet/updateToUseU10#testing-with-robotium) - link leads to `404`. Is this still relevant? I'm not really sure how to advise here...
- [License your app](https://github.com/Esri/mapbook-android/tree/puneet/updateToUseU10#licensing) - link leads to `404`. Can you update to the new dev-x site [licensing](https://developers.arcgis.com/android/license-and-deployment/) doc?

### docs/README

- [PopUp](https://raw.githubusercontent.com/Esri/mapbook-android/puneet/updateToUseU10/docs/README.md) - links to `404`. Since this is referring to a deprecated resource named 'essential vocabulary', perhaps we swap this link for the new dev-x [glossary's Pop-up entry](https://developers.arcgis.com/documentation/glossary/pop-up/)?
- [The **identify** operation](https://github.com/Esri/mapbook-android/blob/puneet/updateToUseU10/docs/README.md#identify)... - links to `404`. Perhaps we can updated this with a new link to the API ref?
- [obtained from the map as **operational layers**.](https://github.com/Esri/mapbook-android/blob/puneet/updateToUseU10/docs/README.md#toc-legend-and-bookmarks) - links to `404`. Maybe you can update the link to the API ref? 
- [...must first be **loaded** before...](https://github.com/Esri/mapbook-android/blob/puneet/updateToUseU10/docs/README.md#mobile-map-packages) - links to `404`. Is there a dev-x doc you can link to here?
- [...uses **geocoding** to transform an address...](https://github.com/Esri/mapbook-android/blob/puneet/updateToUseU10/docs/README.md#suggestions--search) - links to `404`. Is there a dev-x doc you can link to here?

**Comment by puneet-pdx** [comment]
@esreli 
>Solo.takeScreenshot() - link leads to 404. Is this still relevant? I'm not really sure how to advise here...
The robotium website is down and the domain is up for grabs. I have taken out the whole line that refers to the link

I have addressed your comments. Please have another look.

**Review by esreli — APPROVED** [review]
LGTM 👍

**Pull request merged**
